backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'ui'
    label: 'Social media'
    files:
    - name: 'social_media'
      label: 'Social media'
      format: 'json'
      file: 'assets/content/ui/social.json'
      slug: '{{slug}}'
      editor:
        preview: false
      widget: 'object'
      fields:
        - name: 'social_media_links'
          label: 'Linki'
          format: 'json'
          widget: 'list'
          fields:
            - { label: 'Social media - nazwa', name: 'social_media_name', widget: 'string' }
            - { label: 'Social media - link', name: 'social_media_url', widget: 'string' }

  - name: 'pages'
    label: 'Podstrony'
    files:

    - name: 'home'
      label: 'Strona domowa'
      format: 'json'
      file: 'assets/content/pages/home.json'
      slug: '{{slug}}'
      editor:
        preview: false
      fields:
        - { label: 'Slogan/Hasło zachęcające', name: 'home_page_title', widget: 'string' }
        - { label: 'Tekst zachęcający do zadzwonienia', name: 'cta_phone_text', widget: 'string' }
        - { label: 'Numer telefonu', name: 'cta_phone_number', widget: 'string' }
        - { label: 'Godziny otwarcia nagłówek', name: 'company_opening_hours_header', widget: 'string' }
        - { label: 'Godziny otwarcia', name: 'company_opening_hours', widget: 'markdown' }
        - { label: 'Adres restauracji', name: 'company_address', widget: 'markdown' }

    - name: 'events'
      label: 'Imprezy okolicznościowe'
      format: 'json'
      file: 'assets/content/pages/events.json'
      slug: '{{slug}}'
      editor:
        preview: false
      fields:
        - { label: 'Nagłówek strony', name: 'events_page_title', widget: 'string' }
        - { label: 'Numer telefonu dla imprez okolicznościowych', name: 'events_phone_number', widget: 'string' }
        - { label: 'Oferta imprez okolicznościowych', name: 'events_text', widget: 'markdown' }

        - name: 'event_menu'
          label: 'Przykładowe menu'
          format: 'json'
          widget: 'list'
          fields:
            - { label: 'Nazwa zestawu', name: 'event_menu_name', widget: 'string' }
            - { label: 'Zestaw opis', name: 'event_menu_description', widget: 'markdown' }
            - { label: 'Cena zestawu', name: 'event_menu_price', widget: 'number', valueType: 'float' }
            - { label: 'Zdjęcie', name: 'event_menu_photo', widget: 'image' }

  - name: 'menu'
    label: 'Menu restauracji'
    files:
      - name: 'foods'
        label: 'Potrawy'
        format: 'json'
        file: 'assets/content/menu/menu.json'
        slug: '{{slug}}'
        widget: list
        allow_add: true
        create: true
        fields:
          - name: 'categories'
            label: 'Kategorie'
            format: 'json'
            widget: 'object'
            create: true
            fields:
              - { label: 'Kategoria potraw', name: 'category', widget: 'string'}
              - name: 'dishes'
                label: 'Dania'
                format: 'json'
                widget: 'list'
                create: true
                fields:
                  - { label: 'Nazwa potrawy', name: 'dish_name', widget: 'string' }
                  - { label: 'Opis potrawy', name: 'dish_description', widget: 'string' }
                  - { label: 'Ilość/wielkość potrawy', name: 'dish_size', widget: 'string' }
                  - { label: 'Cena potrawy', name: 'dish_price', widget: 'string' }
