backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'ui'
    label: 'Social media'
    files:

    - name: 'social_media'
      label: 'Social media'
      format: 'json'
      file: 'assets/content/ui/social.json'
      slug: '{{slug}}'
      editor:
        preview: false
      fields:
        - { label: 'Facebook link', name: 'facebook', widget: 'string' }
        - { label: 'Instagram link', name: 'instagram', widget: 'string' }

  - name: 'pages'
    label: 'Podstrony'
    files:

    - name: 'home'
      label: 'Strona domowa'
      format: 'json'
      file: 'assets/content/pages/home.json'
      slug: '{{slug}}'
      editor:
        preview: false
      fields:
        - { label: 'Slogan', name: 'slogan', widget: 'string' }
        - { label: 'Numer telefonu', name: 'phone', widget: 'string' }
        - { label: 'Otwarcie nagłówek', name: 'open_header', widget: 'string' }
        - { label: 'Godziny otwarcia', name: 'open_time', widget: 'markdown' }
        - { label: 'Adres restauracji', name: 'address', widget: 'markdown' }

    - name: 'events'
      label: 'Imprezy okolicznościowe'
      format: 'json'
      file: 'assets/content/pages/events.json'
      slug: '{{slug}}'
      editor:
        preview: false
      fields:
        - { label: 'Nagłówek', name: 'title', widget: 'string' }
        - { label: 'Numer telefonu', name: 'phone', widget: 'string' }
        - { label: 'Oferta imprez okolicznościowych', name: 'events_text', widget: 'markdown' }

        - name: 'event_menu'
          label: 'Przykładowe menu'
          format: 'json'
          widget: 'list'
          fields:
            - { label: 'Nazwa zestawu', name: 'event_menu_name', widget: 'string' }
            - { label: 'Zestaw opis', name: 'event_menu_description', widget: 'markdown' }
            - { label: 'Cena zestawu', name: 'event_menu_price', widget: 'number', valueType: 'float' }
            - { label: 'Zdjęcie', name: 'event_menu_photo', widget: 'image' }

  - name: 'menu'
    label: 'Menu restauracji'
    format: 'json'
    folder: 'assets/content/menu'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Tytuł', name: 'title', widget: 'string' }
      - { label: 'Podtytuł', name: 'sub-title', widget: 'string' }

      - name: 'category'
        label: 'Potrawa'
        format: 'json'
        widget: 'list'
        fields:
          - { label: 'Nazwa potrawy', name: 'name', widget: 'string' }
          - { label: 'Opis potrawy', name: 'description', widget: 'string' }
          - { label: 'Ilość/wielkość potrawy', name: 'size', widget: 'string' }
          - { label: 'Cena potrawy', name: 'price', widget: 'string' }
